#!/bin/bash

# Copies needed mod files, cooks, packs and creates metadata
# Usage: first argument is the path to the mod in form: /[driveLetter]/[restOfThePath]
# no '/' at the end
#
# Requirements:
# 1) wcc_lite in PATH
# 2) Mod directory structure:
#      [modWorkDir]/Cooked (cooked files)
#	   [modWorkDir]/Uncooked (uncooked files)
#	   [modWorkDir]/Packed/[modReadyFolder] (mod package)
#

# ASSET FILES BEGIN
assetFile[0]="/gameplay/abilities/geralt_skills.xml"
assetFile[1]="/gameplay/abilities/geralt_stats.xml"
assetFile[2]="/gameplay/abilities/effects_potions.xml"
assetFile[3]="/gameplay/abilities/effects_mutagens.xml"


assetFile[4]="/gameplay/items/def_item_alchemy_oils.xml"
assetFile[5]="/gameplay/items/def_item_quality.xml"
assetFile[6]="/gameplay/items/def_item_alchemy_potion.xml"
assetFile[7]="/gameplay/items/def_item_ingredients.xml"
assetFile[8]="/gameplay/items/def_item_bolts.xml"
assetFile[9]="/gameplay/items/def_loot_monsters.xml"

assetFile[10]="/gameplay/items/def_item_crafting_armor.xml"
assetFile[11]="/gameplay/items/def_item_crafting_boots.xml"
assetFile[12]="/gameplay/items/def_item_crafting_gloves.xml"
assetFile[13]="/gameplay/items/def_item_crafting_pants.xml"
assetFile[14]="/gameplay/items/def_item_cooking_recipes.xml"
assetFile[15]="/gameplay/items/def_item_crafting_weapons.xml"
assetFile[16]="/gameplay/items/def_item_edibles.xml"
assetFile[17]="/gameplay/items/def_item_alchemy_petards.xml"
assetFile[18]="/gameplay/items/def_item_upgrades.xml"
assetFile[19]="/gameplay/items/def_loot_containers.xml"
assetFile[20]="/gameplay/items/def_loot_shops.xml"
assetFile[21]="/gameplay/items/def_item_weapons_crossbow.xml"
assetFile[22]="/gameplay/items/def_item_boots.xml"
assetFile[23]="/gameplay/items/def_item_gloves.xml"
assetFile[24]="/gameplay/items/def_item_pants.xml"
assetFile[25]="/gameplay/items/def_item_crafting_recipes_bolts.xml"
assetFile[26]="/gameplay/items/def_item_alchemy_mutagens.xml"

assetFile[27]="/dlc/ep1/data/gameplay/abilities/geralt_skills_ep1.xml"
assetFile[28]="/dlc/ep1/data/gameplay/abilities/monster_base_abl.xml"
assetFile[29]="/dlc/bob/data/gameplay/abilities/geralt_mutations.xml"
assetFile[30]="/dlc/bob/data/gameplay/abilities/effects_ep2.xml"
assetFile[31]="/dlc/bob\data/gameplay/abilities/geralt_skills_ep2.xml"
assetFile[32]="/dlc/bob/data/gameplay/items/def_item_crafting_armor.xml"
assetFile[33]="/dlc/bob/data/gameplay/items/def_item_crafting_boots.xml"
assetFile[34]="/dlc/bob/data/gameplay/items/def_item_crafting_gloves.xml"
assetFile[35]="/dlc/bob/data/gameplay/items/def_item_crafting_pants.xml"
assetFile[36]="/dlc/bob/data/gameplay/items/def_item_crafting_weapons.xml"

assetFile[37]="/gameplay/abilities/effects.xml"
assetFile[38]="/dlc/dlc5/data/gameplay/items/dlc5_shop.xml"
assetFile[39]="/dlc/dlc1/data/gameplay/items/dlc1_shop.xml"
assetFile[40]="/dlc/dlc14/data/gameplay/items/dlc14_shop.xml"
assetFile[41]="/dlc/dlc14/data/gameplay/items/dlc14_items.xml"
assetFile[42]="/dlc/dlc10/data/gameplay/items/dlc10_wolf_armor.xml"
assetFile[43]="/dlc/dlc10/data/gameplay/items/dlc10_wolf_swords.xml"
assetFile[44]="/dlc/ep1/data/gameplay/items/def_item_ep1_runewords.xml"
assetFile[45]="/dlc/ep1/data/gameplay/items/def_item_weapons.xml"
assetFile[46]="/dlc/ep1/data/gameplay/items/def_item_crafting_weapons.xml"
assetFile[47]="/dlc/ep1/data/gameplay/items/def_item_armor.xml"
assetFile[48]="/dlc/ep1/data/gameplay/items/def_item_boots.xml"
assetFile[49]="/dlc/ep1/data/gameplay/items/def_item_gloves.xml"
assetFile[50]="/dlc/ep1/data/gameplay/items/def_item_pants.xml"

assetFile[51]="/gameplay/abilities/common_abilities.xml"
assetFile[52]="/gameplay/items/def_item_armor.xml"
assetFile[53]="/gameplay/items/def_item_crafting_recipes.xml"
assetFile[54]="/gameplay/items/def_item_weapons.xml"
assetFile[55]="/gameplay/items/def_item_armor_relics.xml"
assetFile[56]="/dlc/dlc13/data/gameplay/items/dlc13_items.xml"
assetFile[57]="/dlc/bob/data/gameplay/items/def_item_weapons_crossbows.xml"
assetFile[58]="/dlc/dlc5/data/gameplay/items/dlc5_items.xml"
assetFile[59]="/dlc/dlc1/data/gameplay/items/dlc1_items.xml"

# ASSET FILES END

set -e

modReadyFolder="/G/Witcher3Work/W3EE/LHW3EE/Packed/modLHW3EE"
modContentPath=$modReadyFolder"/content"

inXMLPath="assets"

outXmlPath1="/G/Witcher3Work/W3EE/LHW3EE/Uncooked"
outXmlPath2="/G/Witcher3Work/W3EE/LHW3EE/Cooked"


cp -r ./scripts $modContentPath


if [ ${#assetFile[@]} != 0 ];
then
	for i in "${assetFile[@]}"
	do
		cp $inXMLPath$i $outXmlPath1$i
		cp $inXMLPath$i $outXmlPath2$i
	done
fi


echo "Files copied OK."

if [ ${#assetFile[@]} != 0 ];
then
	wcc_lite cook -platform=pc -mod=$outXmlPath1 -basedir=$outXmlPath1 -outdir=$outXmlPath2
	wcc_lite pack -dir=$outXmlPath2 -outdir=$modContentPath
	wcc_lite metadatastore -path=$modContentPath
fi
