#!/bin/bash

# Copies needed mod files, cooks, packs and creates metadata
# Usage: first argument is the path to the mod in form: /[driveLetter]/[restOfThePath]
# no '/' at the end
#
# Requirements:
# 1) wcc_lite in PATH
# 2) Mod directory structure:
#      [modWorkDir]/Cooked (cooked files)
#	   [modWorkDir]/Uncooked (uncooked files)
#	   [modWorkDir]/Packed/[modReadyFolder] (mod package)
#

# ASSET FILES BEGIN
assetFile[0]="/gameplay/abilities/geralt_skills.xml"
assetFile[1]="/gameplay/abilities/geralt_stats.xml"
assetFile[2]="/gameplay/abilities/effects_potions.xml"
assetFile[3]="/gameplay/abilities/effects_mutagens.xml"


assetFile[4]="/gameplay/items/def_item_alchemy_oils.xml"
assetFile[5]="/gameplay/items/def_item_quality.xml"
assetFile[6]="/gameplay/items/def_item_alchemy_potion.xml"
assetFile[7]="/gameplay/items/def_item_ingredients.xml"
assetFile[8]="/gameplay/items/def_item_bolts.xml"
assetFile[9]="/gameplay/items/def_loot_monsters.xml"

assetFile[10]="/gameplay/items/def_item_crafting_armor.xml"
assetFile[11]="/gameplay/items/def_item_crafting_boots.xml"
assetFile[12]="/gameplay/items/def_item_crafting_gloves.xml"
assetFile[13]="/gameplay/items/def_item_crafting_pants.xml"
assetFile[14]="/gameplay/items/def_item_cooking_recipes.xml"
assetFile[15]="/gameplay/items/def_item_crafting_weapons.xml"
assetFile[16]="/gameplay/items/def_item_edibles.xml"

assetFile[17]="/dlc/ep1/data/gameplay/abilities/geralt_skills_ep1.xml"
assetFile[18]="/dlc/bob/data/gameplay/abilities/effects_ep2.xml"
assetFile[19]="/dlc/bob/data/gameplay/items/def_item_crafting_armor.xml"
assetFile[20]="/dlc/bob/data/gameplay/items/def_item_crafting_boots.xml"
assetFile[21]="/dlc/bob/data/gameplay/items/def_item_crafting_gloves.xml"
assetFile[22]="/dlc/bob/data/gameplay/items/def_item_crafting_pants.xml"

assetFile[23]="/gameplay/abilities/effects.xml"


# ASSET FILES END

set -e

modReadyFolder="/G/Witcher3Work/W3EE/LHW3EE/Packed/modLHW3EE"
modContentPath=$modReadyFolder"/content"

inXMLPath="assets"

outXmlPath1="/G/Witcher3Work/W3EE/LHW3EE/Uncooked"
outXmlPath2="/G/Witcher3Work/W3EE/LHW3EE/Cooked"


cp -r ./scripts $modContentPath


if [ ${#assetFile[@]} != 0 ];
then
	for i in "${assetFile[@]}"
	do
		cp $inXMLPath$i $outXmlPath1$i
		cp $inXMLPath$i $outXmlPath2$i
	done
fi


echo "Files copied OK."

if [ ${#assetFile[@]} != 0 ];
then
	wcc_lite cook -platform=pc -mod=$outXmlPath1 -basedir=$outXmlPath1 -outdir=$outXmlPath2
	wcc_lite pack -dir=$outXmlPath2 -outdir=$modContentPath
	wcc_lite metadatastore -path=$modContentPath
fi
